### PR TITLE
Issue #231: Added notifications when plugins are force activated

### PR DESCRIPTION
**Pull request by creativecoder**
I've added this with the goal of providing feedback to users that indicates why plugins are being automatically reactivated.

Implemented by adding a new method, for possibly extending this to work on forced deactivation, at some point in the future.

### CODE REVIEW

**Comment by jrfnl** [comment]
@creativecoder Hi Grant, sorry for not responding to this PR earlier. A lot has changed in TGMPA since you made this PR, but I kind of like the idea and would be open to adding this for the next release.

Would you be willing to submit a new PR against the current develop branch ?

**Comment by creativecoder** [comment]
Yes, I can rebase and submit a new pull request--I'll try to get to that later this week. Thanks, Grant

**Comment by jrfnl** [comment]
@creativecoder Awesome! Thank you. I look forward to it.

**Comment by jrfnl** [comment]
Hi @creativecoder Just wondering if you've had a chance to look at this.

**Comment by creativecoder** [comment]
@jrfnl I've submitted an updated pull request here: #569

**Pull request closed without merging**
