### PR TITLE
Updated the example plugin.

### LINKED ISSUE #555: Test and update the tgm-example-plugin.zip file
Although it still works, with 4.5 coming out the door soon, it would be good to update the example plugin (`tgm-example-plugin.zip`) to match coding standards, update the Plugin URI, versions, etc. Also, the text is not localized.

In general, just could use some cleaning up.

### PR DESCRIPTION
**Pull request by jrfnl**
- Added file header
- Localized and escaped the text string
- Applied best practices and coding standards
- Added readme.txt
- Added license file

Fixes #555 

Tested & found working in WP 4.5

### CODE REVIEW

**Comment by GaryJones** [comment]
I can't easily see the diff, so feel free to merge it yourself.

**Comment by jrfnl** [comment]
> I can't easily see the diff,

Yeah, I know, zip is not the best format for diffing, but it is the way it needs to be in the repo for the demo purpose for which it was included.

Would it be an idea to create a separate repo for maintaining the code of the example plugin ? That would make diffing a breeze when there would be updates (like this one).

> so feel free to merge it yourself.

I'll give Thomas a chance to have a look at it first as it's in response to an issue he opened.

**Comment by GaryJones** [comment]
A separate repo makes sense.

**Comment by jrfnl** [comment]
> A separate repo makes sense.

Created & given you both access. Initial commit is the original file, I've gone through the file history and found no other changes since.
Opened a PR https://github.com/TGMPA/tgm-example-plugin/pull/2 for the changes contained in this PR.

**Comment by jrfnl** [comment]
Oh and just for the record: I've not committed the OSX artefacts which were included in the original zip to the new repo and had removed these from the zip file in this PR as well.

**Pull request merged**
