### PR TITLE
Rename username

### PR DESCRIPTION
**Pull request by elvishp2006**
Rename my username on commit-id 6689847

### CODE REVIEW

**Comment by GaryJones** [comment]
Still no good I'm afraid.

**Comment by elvishp2006** [comment]
I just did the fork, created a new branch and ran the following command to rename my username that was elvis.pereira to elvishp2006 just that.

```shell
git filter-branch -f --commit-filter 'if [ "$GIT_AUTHOR_NAME" = "elvis.pereira" ]; then export GIT_AUTHOR_NAME="elvishp2006"; export GIT_AUTHOR_EMAIL=elvishp2006@gmail.com; fi; git commit-tree "$@"'
```

**Comment by GaryJones** [comment]
Ah, commit name, not a credited name in the content.

https://help.github.com/articles/changing-author-info/

> Warning: This action is destructive to your repository's history. If you're collaborating on a repository with others, it's considered bad practice to rewrite published history. You should only do this in an emergency.
> ...
> Note: Running this script rewrites history for all repository collaborators. After completing these steps, any person with forks or clones must fetch the rewritten history and rebase any local changes into the rewritten history.

Since this repo has 270 forks, and 1000+ stars, and who knows how many people referencing individual commits, and noting the Warning and Note given on the GitHub page, I'm inclined to mark this as wontfix. Thoughts @jrfnl?

**Comment by jrfnl** [comment]
I concur with @GaryJones  - too small a change to make the hassle (and risk of future issues with it) worth it. Sorry.

**Pull request closed without merging**
