### PR TITLE
updated add_submenu_page call to work around Theme Check

### PR DESCRIPTION
**Pull request by galengidman**
Did some digging and found a solution to #475. I guess Theme Check updated at some point which made the 9896b44 fix no longer work.

### CODE REVIEW

**Comment by shivapoudel** [comment]
@GaryJones if set for theme in config then let's by default point submenu to appearance menu, but if it was for plugin then let the user decide. If there exist some logic to check tgmpa is in plugin or in theme directory then it will be smart way to handle those config too.

**Comment by jrfnl** [comment]
Theme Check would just be adjusted to detect this. Closing - downward spiral. See discussion in #460.

**Comment by galengidman** [comment]
Ah, didn't see that. Thanks for pointing me to it.

**Comment by jrfnl** [comment]
FYI: The  [Custom TGMPA Generator](http://tgmpluginactivation.com/download/), which is now available on the website, fixes this.

**Pull request closed without merging**
