### PR TITLE
Pull request for Croatian translation of TGM-Plugin-Activation

### PR DESCRIPTION
**Pull request by dingo-d**
I've added the Croatian translation of the TGM-Plugin-Activation, up for a review.

### CODE REVIEW

**Comment by jrfnl** [comment]
Hi @dingo-d Thank you very much for creating this translation.
Would you mind squashing the commits and issuing the pull request against the feature/additional-translations branch ? That way it will become part of PR #564 where I'm currently collecting the latest versions for the 2.6.0 release.

**Comment by dingo-d** [comment]
Hi! No problem. I'm a bit green in the Git commit/pull requests, I just change the branch from develop to `feature/additional-translations` and make a new pull request, right?

**Comment by jrfnl** [comment]
Hi @dingo-d,

> I'm a bit green in the Git commit/pull requests

Not to worry, we all were once ;-) I'm happy to help you along. Let me know if you have any questions.

> I just change the branch from develop to feature/additional-translations and make a new pull request, right?

Yes, that should work.

Pro-tip (for the future): you can create a new branch at any commit or branch, so you could branch off the `feature/additional-translations` and then pull against it. This will avoid conflicts in case the `develop` branch would have moved on already.

**Comment by dingo-d** [comment]
Ok so I deleted the old fork and created a new one, but this time from `feature/additional-translations` and I made a pull request to it, I hope it's ok now.

**Comment by jrfnl** [comment]
Thanks @dingo-d Sounds good, however I don't see the PR yet ? Did you do the PR against this repo or against your own fork ? It needs to be against this repo for me to be able to merge it in.

**Comment by dingo-d** [comment]
I guess I did something wrong, I can see the PR now #574 Is this ok?

**Comment by jrfnl** [comment]
Absolutely! Thank you so much for bearing with me on this. I've merged it now ;-)

**Comment by dingo-d** [comment]
No problem, happy to help and learn a bit in the process :)

**Pull request closed without merging**
